import { APIRequestContext, expect } from '@playwright/test';
import { LoginClient } from '../endpoints/loginClient';
import { ScanClient } from '../endpoints/scanClient';
import { ResetClient } from '../endpoints/resetClient';
import { AlertsClient } from '../endpoints/alertsClient';
import { Logger } from '../../../utilities/helpers/logger';
import config from '../../../utilities/config/env';

export class AlertLifeCycle {
  private request: APIRequestContext;
  private loginClient: LoginClient;
  public scanClient: ScanClient;
  private resetClient: ResetClient;
  public alertsClient: AlertsClient;
  public authToken: string = '';

  constructor(request: APIRequestContext) {
    this.request = request;
    this.loginClient = new LoginClient(request, config.apiBaseURL);
    this.scanClient = new ScanClient(request, config.apiBaseURL);
    this.resetClient = new ResetClient(request, config.apiBaseURL);
    this.alertsClient = new AlertsClient(request, config.apiBaseURL);
  }

  /**
   * Setup: Login and initialize authentication for all clients
   */
  async setup(username: string, password: string): Promise<void> {
    Logger.info('AlertLifeCycle: Setting up - Logging in...');

    const loginResponse = await this.loginClient.login(username, password);
    expect(loginResponse.status()).toBe(200);

    const loginBody = await loginResponse.json();
    this.authToken = loginBody.token;

    Logger.info(`AlertLifeCycle: Authentication successful, token obtained`);

    // Set token for all clients
    this.scanClient.setAuthToken(this.authToken);
    this.resetClient.setAuthToken(this.authToken);
    this.alertsClient.setAuthToken(this.authToken);
  }

  /**
   * Create a scan and wait for completion
   */
  async scan(scanData: any = { name: 'Test Scan', description: 'A test scan generated by AlertLifeCycle' }): Promise<void> {
    Logger.info('AlertLifeCycle: Creating a new scan...');

    const createResponse = await this.scanClient.createScan(scanData);
    expect(createResponse.status()).toBeLessThanOrEqual(201);

    const createdScan = await createResponse.json();
    Logger.info(`AlertLifeCycle: Scan created with ID: ${createdScan.id}`);

    Logger.info('AlertLifeCycle: Waiting for scan to complete...');
    const completedScan = await this.scanClient.waitForScanCompletion();
    expect(completedScan).toBeTruthy();
    expect(completedScan.status?.toUpperCase()).toMatch(/COMPLETED|SUCCESS/);

    Logger.info(`AlertLifeCycle: Scan completed with status: ${completedScan.status}`);
  }

  /**
   * Cleanup: Reset all data
   */
  async cleanup(): Promise<void> {
    Logger.info('AlertLifeCycle: Cleaning up - Resetting data...');

    const resetResponse = await this.resetClient.reset();
    expect(resetResponse.status()).toBe(200);

    Logger.info('AlertLifeCycle: Data reset successfully');
  }

  /**
   * Get current alerts count
   */
  async getAlertsCount(): Promise<number> {
    return this.alertsClient.getAlertsCount();
  }

  /**
   * Get all alerts
   */
  async getAlerts() {
    const response = await this.alertsClient.getAlerts();
    if (response.status() === 200) {
      return await response.json();
    }
    return [];
  }
}