import { APIRequestContext, expect } from '@playwright/test';
import { LoginClient } from '../endpoints/loginClient';
import { ScanClient } from '../endpoints/scanClient';
import { ResetClient } from '../endpoints/resetClient';
import { PoliciesClient } from '../endpoints/policiesClient';
import { AlertsClient } from '../endpoints/alertsClient';
import { Logger } from '../../../utilities/helpers/logger';
import config from '../../../utilities/config/env';

export class PolicyLifeCycle {
  private request: APIRequestContext;
  private loginClient: LoginClient;
  public scanClient: ScanClient;
  private resetClient: ResetClient;
  public policiesClient: PoliciesClient;
  public alertsClient: AlertsClient;
  public authToken: string = '';
  public userData: any = null;

  constructor(request: APIRequestContext) {
    this.request = request;
    this.loginClient = new LoginClient(request, config.apiBaseURL);
    this.scanClient = new ScanClient(request, config.apiBaseURL);
    this.resetClient = new ResetClient(request, config.apiBaseURL);
    this.policiesClient = new PoliciesClient(request, config.apiBaseURL);
    this.alertsClient = new AlertsClient(request, config.apiBaseURL);
  }

  async setup(username: string, password: string): Promise<void> {
    Logger.info('PolicyLifeCycle: Setting up - Logging in...');

    const loginResponse = await this.loginClient.login(username, password);
    expect(loginResponse.status()).toBe(200);

    const loginBody = await loginResponse.json();
    this.authToken = loginBody.token;
    this.userData = loginBody.user;

    Logger.info('PolicyLifeCycle: Authentication successful, token obtained');

    this.scanClient.setAuthToken(this.authToken);
    this.resetClient.setAuthToken(this.authToken);
    this.policiesClient.setAuthToken(this.authToken);
    this.alertsClient.setAuthToken(this.authToken);
  }

  async createPolicy(policyData: any): Promise<any> {
    Logger.info('PolicyLifeCycle: Creating a new policy...');

    const createResponse = await this.policiesClient.createPolicy(policyData);
    expect(createResponse.status()).toBeLessThanOrEqual(201);

    const createdPolicy = await createResponse.json();
    Logger.info(`PolicyLifeCycle: Policy created with ID: ${createdPolicy.id}`);

    return createdPolicy;
  }

  async scan(scanData: any = { name: 'Test Scan', description: 'A test scan generated by PolicyLifeCycle' }): Promise<void> {
    Logger.info('PolicyLifeCycle: Creating a new scan...');

    const createResponse = await this.scanClient.createScan(scanData);
    expect(createResponse.status()).toBeLessThanOrEqual(201);

    const createdScan = await createResponse.json();
    Logger.info(`PolicyLifeCycle: Scan created with ID: ${createdScan.id}`);

    Logger.info('PolicyLifeCycle: Waiting for scan to complete...');
    const completedScan = await this.scanClient.waitForScanCompletion();
    expect(completedScan).toBeTruthy();
    expect(completedScan.status?.toUpperCase()).toMatch(/COMPLETED|SUCCESS/);

    Logger.info(`PolicyLifeCycle: Scan completed with status: ${completedScan.status}`);
  }

  async cleanup(): Promise<void> {
    Logger.info('PolicyLifeCycle: Cleaning up - Resetting data...');

    const resetResponse = await this.resetClient.reset();
    expect(resetResponse.status()).toBe(200);

    Logger.info('PolicyLifeCycle: Data reset successfully');
  }

  async getPoliciesCount(): Promise<number> {
    return this.policiesClient.getPoliciesCount();
  }

  async getPolicies() {
    const response = await this.policiesClient.getPolicies();
    if (response.status() === 200) {
      return await response.json();
    }
    return [];
  }

  async getAlerts() {
    const response = await this.alertsClient.getAlerts();
    if (response.status() === 200) {
      return await response.json();
    }
    return [];
  }

  async getAlertsCount(): Promise<number> {
    return this.alertsClient.getAlertsCount();
  }
}